### ISSUE TITLE
Jak wypełnić pole "Data otrzymania zaliczki"

### ISSUE THREAD

**Issue by leniartek** [radgost/fakturownia-api-docs#2]
Cześć,
Tworzę poprzez API fakturę zaliczkową jak niżej;
```
"invoice": {
        "kind": "advance",
        "number": null,
        "sell_date": "2019-03-26",
        "issue_date": "2019-03-26",
        "paid_date": "2019-03-25",
        "other_date": "2019-03-25",
        "currency": "PLN",
        "paid": "500,00"
        ...
}
```

Faktura generuje się poprawnie, problem mam jedynie z datą w prawym górnym rogu faktury.

W fakturach zaliczkowych wystawianych ręcznie zawsze jest to "Data otrzymania zaliczki" u mnie zamiast tego jest "Data sprzedaży".

Czy jest możliwość aby poprzez API uzyskać "Data otrzymania zaliczki"?

Dzięki.

**Comment by JuDaniel** [comment]
Cześć,

Należy przesłać dodatkowy atrybut faktury - sell_date_kind: "ADVANCE_RECEIPT_DATE".

```
"invoice": {
  ...
  "sell_date": "2019-03-26",
  "sell_date_kind": "ADVANCE_RECEIPT_DATE",
  ...
}
```

Jeżeli pojawią się dodatkowe pytania, pozostajemy do dyspozycji,
Pozdrawiamy,
zespół Fakturownia.pl

**Comment by leniartek** [comment]
Dzięki wielkie, chyba brakuje tej informacji w dokumentacji warto ją dodać :)
